### ISSUE TITLE
Test that makes no sense?

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Products.GenericSetup#44]
When running the tests against current master under Python 2.7 using the standard `bin/test` script they all complete successfully. However, running them via `tox` produces non-deterministic errors. Example:

```python
Failure in test test_runAllExportSteps_empty (Products.GenericSetup.tests.test_tool.SetupToolTests)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/jens/src/Products.GenericSetup/Products/GenericSetup/tests/test_tool.py", line 890, in test_runAllExportSteps_empty
    self.assertEqual(result['steps'][1], 'step_registries')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: u'toolset' != 'step_registries'
```

The test code (see https://github.com/zopefoundation/Products.GenericSetup/blob/master/Products/GenericSetup/tests/test_tool.py#L882) appears to assume that `result` from a call to `tool.runAllExportSteps()` has a fixed order of steps. But that makes no sense when I look at how the result is put together. In `listExportSteps` the steps are combined from two `set` instances, which obviously don't have a sorting order.

Is the assumption of a fixed order wrong or is the implementation wrong which disregards any order?

**Comment by tseaver** [comment]
The tests are borked (I actually have three which are flaky under tox for the same reason, along with another, apparently unrelated one).
