### ISSUE TITLE
minor error when running linter

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.GenericSetup#93]
The flake8-html plugin wants to write into a subdirectory of parts - but the parts directory is not present. The flake8 check runs, but obviously not html gets generated.

```
❯ tox -e=flake8
flake8 installed: flake8==3.8.1,flake8-debugger==3.2.1,flake8-html==0.4.1,importlib-metadata==1.6.0,Jinja2==2.11.2,MarkupSafe==1.1.1,mccabe==0.6.1,Products.GenericSetup==2.0.3.dev0,pycodestyle==2.6.0,pyflakes==2.2.0,Pygments==2.6.1,zipp==3.1.0
flake8 run-test-pre: PYTHONHASHSEED='1702982963'
flake8 run-test: commands[0] | - flake8 --format=html --htmldir=/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/parts/flake8 --doctests Products setup.py
Traceback (most recent call last):
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/main/application.py", line 333, in initialize
    self.make_formatter()
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/main/application.py", line 226, in make_formatter
    self.formatter = formatter_class(self.options)
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/plugins/manager.py", line 131, in execute
    return self.plugin(*args, **kwargs)  # pylint: disable=not-callable
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8/formatting/base.py", line 51, in __init__
    self.after_init()
  File "/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/.tox/flake8/lib/python3.6/site-packages/flake8_html/plugin.py", line 89, in after_init
    os.mkdir(self.outdir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jugmac00/Repos/zopefoundation/Products.GenericSetup/parts/flake8'
flake8 run-test: commands[1] | flake8 --doctests Products setup.py
_________________________________________________________________ summary _________________________________________________________________
  flake8: commands succeeded
  congratulations :)
```

**Comment by dataflake** [comment]
I have closed the PR because I added a fix on `master`. Your fix would have caused the specific thing the tox configuration was trying to avoid, yet another toplevel folder messing up the package root folder.
